kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-helm-components
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAsRange
  uidRangeMax: 1001 
  uidRangeMin: 1001
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
  ranges: 
  - max: 1001
    min: 1001
supplementalGroups:
  type: MustRunAs
users: []
groups: []
