apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ds-files
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 6Gi
