apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  labels:
    app: converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      volumes:
        - name: ds-files
          persistentVolumeClaim:
            claimName: ds-files
        - name: ds-license
          configMap:
            name: license
      containers:
        - name: converter
          image: onlyoffice/4testing-ds-converter:latest
          envFrom:
          - secretRef:
              name: db
          - secretRef:
              name: jwt
          - configMapRef:
              name: documentserver
          volumeMounts:
          - name: ds-files
            mountPath: /var/lib/onlyoffice/documentserver/App_Data/cache/files
          - name: ds-license
            mountPath: /var/www/onlyoffice/Data
            readOnly: true