apiVersion: apps/v1
kind: Deployment
metadata:
  name: docservice
  labels:
    app: docservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docservice
  template:
    metadata:
      labels:
        app: docservice
    spec:
      # topologySpreadConstraints:
      # - maxSkew: 1
        # topologyKey: doks.digitalocean.com/node-pool
        # whenUnsatisfiable: DoNotSchedule
        # labelSelector:
          # matchLabels:
            # app: docservice
      volumes:
        - name: ds-files
          persistentVolumeClaim:
            claimName: ds-files
        - name: ds-license
          configMap:
            name: license
      containers:
        - name: proxy
          image: onlyoffice/4testing-ds-proxy:latest
          ports:
            - containerPort: 8888
          volumeMounts:
          - name: ds-files
            mountPath: /var/lib/onlyoffice/documentserver/App_Data/cache/files

        - name: docservice
          image: onlyoffice/4testing-ds-docservice:latest
          envFrom:
          - secretRef:
              name: db
          - secretRef:
              name: jwt
          - configMapRef:
              name: documentserver
          volumeMounts:
          - name: ds-files
            mountPath: /var/lib/onlyoffice/documentserver/App_Data/cache/files
          - name: ds-license
            mountPath: /var/www/onlyoffice/Data
            readOnly: true

        - name: spellchecker
          image: onlyoffice/4testing-ds-spellchecker:latest