apiVersion: apps/v1
kind: Deployment
metadata:
  name: docservice
  labels:
    app: docservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docservice
  template:
    metadata:
      labels:
        app: docservice
    spec:
      # topologySpreadConstraints:
      # - maxSkew: 1
        # topologyKey: doks.digitalocean.com/node-pool
        # whenUnsatisfiable: DoNotSchedule
        # labelSelector:
          # matchLabels:
            # app: docservice
      volumes:
        - name: ds-files
          persistentVolumeClaim:
            claimName: ds-files
        - name: ds-license
          secret:
            secretName: license
      containers:
        - name: proxy
          image: onlyoffice/docs-proxy-de:6.2.1.94
          ports:
            - containerPort: 8888
          envFrom:
          - configMapRef:
              name: documentserver
          volumeMounts:
          - name: ds-files
            mountPath: /var/lib/onlyoffice/documentserver/App_Data/cache/files

        - name: docservice
          image: onlyoffice/docs-docservice-de:6.2.1.94
          ports:
            - containerPort: 8000
          env:
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgresql-password
          - name: AMQP_PWD
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: rabbitmq-password
          envFrom:
          - secretRef:
              name: jwt
          - configMapRef:
              name: documentserver
          volumeMounts:
          - name: ds-files
            mountPath: /var/lib/onlyoffice/documentserver/App_Data/cache/files
          - name: ds-license
            mountPath: /var/www/onlyoffice/Data
            readOnly: true
