{{- if .Values.wopi.keys.generation }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "wopi-binding") }}
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-delete
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if .Values.commonAnnotations }}
    {{- include "ds.annotations.commonAnnotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "wopi-sa") }}
  namespace: {{ include "ds.namespace" . | quote }}
roleRef:
  kind: Role
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "wopi-role") }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
