apiVersion: v2
name: docs
kubeVersion: '>=1.19.0-0'
description: ONLYOFFICE Docs is a secure, open-source office suite for document collaboration.
type: application
keywords:
  - office
  - office-suite
  - onlyoffice
  - documents
  - spreadsheets
  - presentations
  - forms
  - pdf
  - collaboration
  - productivity
home: https://onlyoffice.com
sources:
  - https://github.com/ONLYOFFICE
  - https://github.com/ONLYOFFICE/DocumentServer
icon: https://avatars.githubusercontent.com/u/1426033
version: 6.2.0
appVersion: 9.5.0
