apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  rules:
  - host:
    http:
      paths:
      - path: /grafana/
        backend:
          serviceName: grafana
          servicePort: 80
