kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-docs-components
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 101
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
  ranges:
  - max: 101
    min: 101
supplementalGroups:
  type: MustRunAs
users: []
groups: []
seccompProfiles:
- runtime/default
