kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-docs-components
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAsRange
  uidRangeMax: 101 
  uidRangeMin: 101
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
  ranges: 
  - max: 101
    min: 101
supplementalGroups:
  type: MustRunAs
users: []
groups: []
