---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: scc-docs-components
allowPrivilegedContainer: false
users: []
groups: []
runAsUser:
  type: MustRunAs
  uid: 101
fsGroup:
  type: MustRunAs
  ranges:
  - max: 101
    min: 101
supplementalGroups:
  type: MustRunAs
seLinuxContext:
  type: MustRunAs
