---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: scc-helm-components
allowPrivilegedContainer: false
users: []
groups: []
runAsUser:
  type: MustRunAs
  uid: 1001
fsGroup:
  type: MustRunAs
  ranges:
  - max: 1001
    min: 1001
supplementalGroups:
  type: MustRunAs
seLinuxContext:
  type: MustRunAs
seccompProfiles:
- runtime/default
