apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs-custom-resources
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs-buffer
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
