apiVersion: v1
kind: Pod
metadata:
  name: docs-custom-resources
spec:
  #imagePullSecrets:
  #- name: mysecret
  volumes:
  - name: custom-resources
    persistentVolumeClaim:
      claimName: docs-custom-resources
  containers:
  - name: docs-custom-resources
    image: onlyoffice/docs-utils:9.3.1-1
    command: ["/bin/sh", "-c"]
    args:
    - mkdir -p /resources/custom-k8s && tail -f /dev/null
    #securityContext:
    #  runAsUser: 0
    volumeMounts:
    - name: custom-resources
      mountPath: /resources
