apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  labels:
    app: converter
spec:
  replicas: {{ .Values.converter.replicas }}
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    {{- if .Values.converter.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.converter.podAnnotations }}
        {{ $key }}: {{ tpl $value $ }}
        {{- end }}
    {{- end }}
    spec:
      {{ if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.securityContext.converter.runAsUser }}
        runAsGroup: {{ .Values.securityContext.converter.runAsGroup }}
      {{ end }}
      affinity:
        podAntiAffinity:
        {{- if eq .Values.antiAffinity.type "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - converter
              topologyKey: {{ .Values.antiAffinity.topologyKey }}
            weight: {{ .Values.antiAffinity.weight }}
        {{- else if eq .Values.antiAffinity.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - converter
            topologyKey: {{ .Values.antiAffinity.topologyKey }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: ds-files
          persistentVolumeClaim:
            claimName: {{ template "ds.pvc.name" . }}
        - name: ds-license
          {{- if .Values.license.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.license.existingClaim }}
          {{- else }}
          secret:
            secretName: {{ template "ds.license.secretName" . }}
          {{- end }}
        {{ if .Values.extraConf.configMap }}
        - name: custom-file
          configMap:
            name: {{ .Values.extraConf.configMap }}
        {{ end }}
        {{ if .Values.extraThemes.configMap }}
        - name: custom-themes
          configMap:
            name: {{ .Values.extraThemes.configMap }}
        {{ end }}
      containers:
        - name: converter
          image: {{ .Values.converter.containerImage }}
          imagePullPolicy: {{ .Values.converter.imagePullPolicy }}
          resources: {{- toYaml .Values.converter.resources | nindent 12 }}
          env:
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: {{ template "ds.postgresql.secretName" . }}
                key: {{ .Values.connections.dbSecretKeyName }}
          - name: AMQP_PWD
            valueFrom:
              secretKeyRef:
                name: {{ template "ds.rabbitmq.secretName" . }}
                key: {{ .Values.connections.amqpSecretKeyName }}
          envFrom:
          - secretRef:
              name: {{ template "ds.jwt.secretName" . }}
          - configMapRef:
              name: documentserver
          volumeMounts:
          - name: ds-files
            mountPath: /var/lib/{{ .Values.product.name }}/documentserver/App_Data/cache/files
          - name: ds-license
            mountPath: /var/www/{{ .Values.product.name }}/Data
            {{- if not .Values.license.existingClaim }}
            readOnly: true
            {{- end }}
          {{ if .Values.extraConf.configMap }}
          - name: custom-file
            mountPath: /etc/{{ .Values.product.name }}/documentserver/{{ .Values.extraConf.filename }}
            subPath: {{ .Values.extraConf.filename }}
          {{ end }}
          {{ if .Values.extraThemes.configMap }}
          - name: custom-themes
            mountPath: /var/www/{{ .Values.product.name }}/documentserver/web-apps/apps/common/main/resources/themes/{{ .Values.extraThemes.filename }}
            subPath: {{ .Values.extraThemes.filename }}
          {{ end }}
