apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "converter") }}
  namespace: {{ include "ds.namespace" . | quote }}
  labels:
    app: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "converter") }}
    {{- if .Values.commonLabels }}
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.converter.annotations }}
  {{- $dictValue := default .Values.commonAnnotations .Values.converter.annotations }}
  annotations: {{- include "ds.annotations.commonAnnotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.converter.autoscaling.enabled }}
  replicas: {{ .Values.converter.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "converter") }}
      {{- if .Values.commonLabels }}
      {{- include "ds.labels.commonLabels" . | trim | nindent 6 }}
      {{- end }}
  {{- if .Values.converter.updateStrategy }}
  strategy: {{- toYaml .Values.converter.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "converter") }}
        {{- if .Values.commonLabels }}
        {{- include "ds.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if .Values.converter.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.converter.podAnnotations }}
        {{ $key }}: {{ tpl $value $ }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "ds.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- toYaml .Values.podSecurityContext.converter | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity.type "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ include "ds.resources.name" (list . .Values.commonNameSuffix "converter") }}
              topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
            weight: {{ .Values.podAntiAffinity.weight }}
          {{- else if eq .Values.podAntiAffinity.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "ds.resources.name" (list . .Values.commonNameSuffix "converter") }}
            topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
          {{- end }}
          {{- with .Values.converter.customPodAntiAffinity }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.converter.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.converter.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if or .Values.nodeSelector .Values.converter.nodeSelector }}
      nodeSelector: {{ toYaml (default .Values.nodeSelector .Values.converter.nodeSelector) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.converter.tolerations }}
      tolerations: {{ toYaml (default .Values.tolerations .Values.converter.tolerations) | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      volumes:
        {{- if not .Values.persistence.storageS3 }}
        - name: ds-files
          persistentVolumeClaim:
            claimName: {{ template "ds.pvc.name" . }}
        {{- end }}
        - name: ds-license
          {{- if .Values.license.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.license.existingClaim }}
          {{- else }}
          secret:
            secretName: {{ template "ds.license.secretName" . }}
          {{- end }}
        {{- if .Values.extraConf.configMap }}
        - name: custom-file
          configMap:
            name: {{ .Values.extraConf.configMap }}
        {{- end }}
        {{- if .Values.extraThemes.configMap }}
        - name: custom-themes
          configMap:
            name: {{ .Values.extraThemes.configMap }}
        {{- end }}
        {{- with .Values.converter.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      terminationGracePeriodSeconds: {{ .Values.converter.terminationGracePeriodSeconds }}
      {{- if .Values.converter.hostAliases }}
      hostAliases: {{- toYaml .Values.converter.hostAliases | nindent 8 }}
      {{- end }}
      {{- with .Values.converter.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: converter
          {{- if .Values.global }}
          image: {{ include "ds.imageRepository" (list . .Values.converter.image.repository) }}:{{ .Values.converter.image.tag }}
          {{- else }}
          image: {{ .Values.converter.image.repository }}:{{ .Values.converter.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.converter.image.pullPolicy }}
          {{- if .Values.converter.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.converter.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.converter.lifecycleHooks }}
          lifecycle: {{- toYaml .Values.converter.lifecycleHooks | nindent 12 }}
          {{- end }}
          resources: {{- toYaml .Values.converter.resources | nindent 12 }}
          env:
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: {{ template "ds.db.secretName" . }}
                key: {{ .Values.connections.dbSecretKeyName }}
          - name: AMQP_PWD
            valueFrom:
              secretKeyRef:
                name: {{ template "ds.rabbitmq.secretName" . }}
                key: {{ .Values.connections.amqpSecretKeyName }}
          - name: REDIS_SERVER_PWD
            valueFrom:
              secretKeyRef:
                name: {{ template "ds.redis.secretName" . }}
                key: {{ .Values.connections.redisSecretKeyName }}
          {{- if eq .Values.connections.redisConnectorName "ioredis" }}
          - name: REDIS_SENTINEL_PWD
            valueFrom:
              secretKeyRef:
                name: {{ template "ds.redis.sentinel.secretName" . }}
                key: {{ .Values.connections.redisSentinelSecretKeyName }}
          {{- end }}
          {{- with .Values.converter.extraEnvVars }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          envFrom:
          - secretRef:
              name: {{ template "ds.jwt.secretName" . }}
          - secretRef:
              name: {{ template "ds.secureLinkSecret.secretName" . }}
          {{- if .Values.wopi.enabled }}
          {{- if or .Values.wopi.keys.generation .Values.wopi.keys.newKeysExistingSecret }}
          - secretRef:
              {{- if .Values.wopi.keys.newKeysExistingSecret }}
              name: {{ tpl .Values.wopi.keys.newKeysExistingSecret $ }}
              {{- else }}
              name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "docs-wopi-keys") }}
              {{- end }}
          {{- end }}
          {{- if or .Values.wopi.keys.generation .Values.wopi.keys.oldKeysExistingSecret }}
          - secretRef:
              {{- if .Values.wopi.keys.oldKeysExistingSecret }}
              name: {{ tpl .Values.wopi.keys.oldKeysExistingSecret $ }}
              {{- else }}
              name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "docs-wopi-keys-old") }}
              {{- end }}
          {{- end }}
          {{- end }}
          - configMapRef:
              name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "documentserver") }}
          volumeMounts:
          {{- if not .Values.persistence.storageS3 }}
          - name: ds-files
            mountPath: /var/lib/{{ .Values.product.name }}/documentserver/App_Data/cache/files
          {{- end }}
          - name: ds-license
            mountPath: /var/www/{{ .Values.product.name }}/Data
            {{- if not .Values.license.existingClaim }}
            readOnly: true
            {{- end }}
          {{- if .Values.extraConf.configMap }}
          - name: custom-file
            mountPath: /etc/{{ .Values.product.name }}/documentserver/{{ .Values.extraConf.filename }}
            subPath: {{ .Values.extraConf.filename }}
          {{- end }}
          {{- if .Values.extraThemes.configMap }}
          - name: custom-themes
            mountPath: /var/www/{{ .Values.product.name }}/documentserver/web-apps/apps/common/main/resources/themes/{{ .Values.extraThemes.filename }}
            subPath: {{ .Values.extraThemes.filename }}
          {{- end }}
          {{- with .Values.converter.extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
