apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.docservice.name }}
  labels:
    app: {{ .Values.docservice.app }}
spec:
  replicas: {{ .Values.docservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.docservice.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.docservice.app }}
    spec:
      # topologySpreadConstraints:
      # - maxSkew: 1
        # topologyKey: doks.digitalocean.com/node-pool
        # whenUnsatisfiable: DoNotSchedule
        # labelSelector:
          # matchLabels:
            # app: docservice
      volumes:
        - name: {{ .Values.pvc.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
        - name: ds-license
          secret:
            secretName: license
      containers:
        - name: proxy
          image: {{ .Values.docservice.proxyContainerImage }}
          ports:
            - containerPort: {{ .Values.docservice.proxyContainerPort }}
          envFrom:
          - configMapRef:
              name: {{ .Values.docservice.configMap }}
          volumeMounts:
          - name: {{ .Values.pvc.name }}
            mountPath: /var/lib/onlyoffice/documentserver/App_Data/cache/files

        - name: docservice
          image: {{ .Values.docservice.docserviceContainerImage }}
          ports:
            - containerPort: {{ .Values.docservice.docserviceContainerPort }}
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.database.name }}
                key: {{ .Values.secrets.database.dbUser }}
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.database.name }}
                key: {{ .Values.secrets.database.dbPassword }}
          - name: AMQP_PWD
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: rabbitmq-password
          envFrom:
          - secretRef:
              name: jwt
          - configMapRef:
              name: {{ .Values.docservice.configMap }}
          volumeMounts:
          - name: {{ .Values.pvc.name }}
            mountPath: /var/lib/onlyoffice/documentserver/App_Data/cache/files
          - name: ds-license
            mountPath: /var/www/onlyoffice/Data
            readOnly: true
