apiVersion: apps/v1
kind: Deployment
metadata:
  name: docservice
  labels:
    app: docservice
spec:
  replicas: {{ .Values.docservice.replicas }}
  selector:
    matchLabels:
      app: docservice
  template:
    metadata:
      labels:
        app: docservice
    spec:
      # topologySpreadConstraints:
      # - maxSkew: 1
        # topologyKey: doks.digitalocean.com/node-pool
        # whenUnsatisfiable: DoNotSchedule
        # labelSelector:
          # matchLabels:
            # app: docservice
      volumes:
        - name: ds-files
          persistentVolumeClaim:
            claimName: ds-files
        - name: ds-license
          secret:
            secretName: license
      containers:
        - name: proxy
          image: {{ .Values.docservice.proxyContainerImage }}
          ports:
            - containerPort: 8888 
          envFrom:
          - configMapRef:
              name: documentserver
          volumeMounts:
          - name: ds-files
            mountPath: /var/lib/onlyoffice/documentserver/App_Data/cache/files

        - name: docservice
          image: {{ .Values.docservice.containerImage }}
          ports:
            - containerPort: 8000 
          env:
          {{ if .Values.connections.dbDefault }}
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgresql-password
          {{ end }}

          {{ if .Values.connections.amqpDefault }}
          - name: AMQP_PWD
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: rabbitmq-password
          {{ end }}
          envFrom:
          - secretRef:
              {{ if not .Values.connections.dbDefault }}
              name: dbsecret
              {{ end }}

              {{ if not .Values.connections.amqpDefault }}
              name: amqpsecret
              {{ end }}
              name: jwt
          - configMapRef:
              name: documentserver
          volumeMounts:
          - name: ds-files
            mountPath: /var/lib/onlyoffice/documentserver/App_Data/cache/files
          - name: ds-license
            mountPath: /var/www/onlyoffice/Data
            readOnly: true
