apiVersion: apps/v1
kind: Deployment
metadata:
  name: docservice
  namespace: {{ include "ds.namespace" . | quote }}
  labels:
    app: docservice
    {{- if .Values.commonLabels }}
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.docservice.annotations }}
  {{- $dictValue := default .Values.commonAnnotations .Values.docservice.annotations }}
  annotations: {{- include "ds.annotations.commonAnnotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.docservice.autoscaling.enabled }}
  replicas: {{ .Values.docservice.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: docservice
      {{- if .Values.commonLabels }}
      {{- include "ds.labels.commonLabels" . | trim | nindent 6 }}
      {{- end }}
  {{- if .Values.docservice.updateStrategy }}
  strategy: {{- toYaml .Values.docservice.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: docservice
        {{- if .Values.commonLabels }}
        {{- include "ds.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if .Values.docservice.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.docservice.podAnnotations }}
        {{ $key }}: {{ tpl $value $ }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "ds.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- toYaml .Values.podSecurityContext.docservice | nindent 8 }}
      {{- end }}
      # topologySpreadConstraints:
      # - maxSkew: 1
        # topologyKey: doks.digitalocean.com/node-pool
        # whenUnsatisfiable: DoNotSchedule
        # labelSelector:
          # matchLabels:
            # app: docservice
      affinity:
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity.type "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - docservice
              topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
            weight: {{ .Values.podAntiAffinity.weight }}
          {{- else if eq .Values.podAntiAffinity.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - docservice
            topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
          {{- end }}
          {{- with .Values.docservice.customPodAntiAffinity }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.docservice.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.docservice.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      volumes:
        {{- if not .Values.persistence.storageS3 }}
        - name: ds-files
          persistentVolumeClaim:
            claimName: {{ template "ds.pvc.name" . }}
        {{- end }}
        - name: ds-license
          {{- if .Values.license.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.license.existingClaim }}
          {{- else }}
          secret:
            secretName: {{ template "ds.license.secretName" . }}
          {{- end }}
        {{- if .Values.extraConf.configMap }}
        - name: custom-file
          configMap:
            name: {{ .Values.extraConf.configMap }}
        {{- end }}
        {{- if .Values.extraThemes.configMap }}
        - name: custom-themes
          configMap:
            name: {{ .Values.extraThemes.configMap }}
        {{- end }}
        {{- if not .Values.proxy.welcomePage.enabled }}
        - name: ds-welcome-page
          configMap:
            name: ds-welcome-page
        {{- end }}
      {{- with .Values.docservice.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: proxy
          image: {{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          {{- if .Values.proxy.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.proxy.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.proxy.containerPorts.http }}
          {{- if .Values.proxy.startupProbe.enabled }}
          startupProbe: {{- omit .Values.proxy.startupProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.proxy.readinessProbe.enabled }}
          readinessProbe: {{- omit .Values.proxy.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.proxy.livenessProbe.enabled }}
          livenessProbe: {{- omit .Values.proxy.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources: {{ toYaml .Values.proxy.resources | nindent 12 }}
          {{- if or .Values.proxy.infoAllowedIP .Values.proxy.infoAllowedUser }}
          env:
          {{- if .Values.proxy.infoAllowedIP }}
          - name: INFO_ALLOWED_IP
            value: {{ join " " .Values.proxy.infoAllowedIP }}
          {{- end }}
          {{- if .Values.proxy.infoAllowedUser }}
          - name: INFO_ALLOWED_USER
            value: {{ .Values.proxy.infoAllowedUser }}
          - name: INFO_ALLOWED_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "ds.info.secretName" . }}
                key: {{ .Values.proxy.infoAllowedSecretKeyName }}
          {{- end }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: documentserver
          volumeMounts:
          {{- if not .Values.persistence.storageS3 }}
          - name: ds-files
            mountPath: /var/lib/{{ .Values.product.name }}/documentserver/App_Data/cache/files
          {{- end }}
          {{- if .Values.extraThemes.configMap }}
          - name: custom-themes
            mountPath: /var/www/{{ .Values.product.name }}/documentserver/web-apps/apps/common/main/resources/themes/{{ .Values.extraThemes.filename }}
            subPath: {{ .Values.extraThemes.filename }}
          {{- end }}
          {{- if not .Values.proxy.welcomePage.enabled }}
          - name: ds-welcome-page
            mountPath: /etc/nginx/includes/ds-example.conf
            subPath: ds-example.conf
          {{- end }}

        - name: docservice
          image: {{ .Values.docservice.image.repository }}:{{ .Values.docservice.image.tag }}
          imagePullPolicy: {{ .Values.docservice.image.pullPolicy }}
          {{- if .Values.docservice.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.docservice.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.docservice.containerPorts.http }}
          {{- if .Values.docservice.startupProbe.enabled }}
          startupProbe: {{- omit .Values.docservice.startupProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.docservice.readinessProbe.enabled }}
          readinessProbe: {{- omit .Values.docservice.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.docservice.livenessProbe.enabled }}
          livenessProbe: {{- omit .Values.docservice.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources: {{ toYaml .Values.docservice.resources | nindent 12 }}
          env:
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: {{ template "ds.db.secretName" . }}
                key: {{ .Values.connections.dbSecretKeyName }}
          - name: AMQP_PWD
            valueFrom:
              secretKeyRef:
                name: {{ template "ds.rabbitmq.secretName" . }}
                key: {{ .Values.connections.amqpSecretKeyName }}
          - name: REDIS_SERVER_PWD
            valueFrom:
              secretKeyRef:
                name: {{ template "ds.redis.secretName" . }}
                key: {{ .Values.connections.redisSecretKeyName }}
          envFrom:
          - secretRef:
              name: {{ template "ds.jwt.secretName" . }}
          - configMapRef:
              name: documentserver
          volumeMounts:
          {{- if not .Values.persistence.storageS3 }}
          - name: ds-files
            mountPath: /var/lib/{{ .Values.product.name }}/documentserver/App_Data/cache/files
          {{- end }}
          - name: ds-license
            mountPath: /var/www/{{ .Values.product.name }}/Data
            {{- if not .Values.license.existingClaim }}
            readOnly: true
            {{- end }}
          {{- if .Values.extraConf.configMap }}
          - name: custom-file
            mountPath: /etc/{{ .Values.product.name }}/documentserver/{{ .Values.extraConf.filename }}
            subPath: {{ .Values.extraConf.filename }}
          {{- end }}
          {{- if .Values.extraThemes.configMap }}
          - name: custom-themes
            mountPath: /var/www/{{ .Values.product.name }}/documentserver/web-apps/apps/common/main/resources/themes/{{ .Values.extraThemes.filename }}
            subPath: {{ .Values.extraThemes.filename }}
          {{- end }}
