apiVersion: apps/v1
kind: Deployment
metadata:
  name: spellchecker
  labels:
    app: spellchecker
spec:
  replicas: {{ .Values.spellchecker.replicas }}
  selector:
    matchLabels:
      app: spellchecker
  template:
    metadata:
      labels:
        app: spellchecker
    spec:
      volumes:
        - name: ds-license
          secret:
            secretName: license
      containers:
        - name: spellchecker
          image: {{ .Values.spellchecker.containerImage }}
          env:
          {{ if .Values.connections.dbDefault }}
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgresql-password  
          {{ end }}
          envFrom:
          - secretRef:
              {{ if not .Values.connections.dbDefault }}
              name: dbsecret
              {{ end }}
              name: jwt
          - configMapRef:
              name: documentserver
          ports:
            - containerPort: 8080 
