{{- if .Values.converter.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: converter-hpa
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: converter
  minReplicas: {{ .Values.converter.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.converter.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.converter.autoscaling.targetCPU.enabled }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.converter.autoscaling.targetCPU.utilizationPercentage }}
  {{- end }}
  {{- if .Values.converter.autoscaling.targetMemory.enabled }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.converter.autoscaling.targetMemory.utilizationPercentage }}
  {{- end }}
  {{- with .Values.converter.autoscaling.customMetricsType }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.converter.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
