apiVersion: v1
kind: Secret
metadata:
  name: jwt
type: Opaque
#immutable: true
stringData:
  JWT_ENABLED: {{ .Values.jwt.enabled | quote }}
  {{ if .Values.jwt.enabled }}
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
  JWT_HEADER: {{ .Values.jwt.header | quote }}
  JWT_IN_BODY: {{ .Values.jwt.inBody | quote }}
  {{ end }}
