{{- if eq (include "ds.rabbitmq.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq
type: Opaque
stringData:
  {{ .Values.connections.amqpSecretKeyName }}: {{ include "ds.rabbitmq.password" . | quote }}
{{- end }}
