{{- if and .Values.gateway.enabled .Values.gateway.ssl.enabled .Values.gateway.letsencrypt.enabled (not .Values.gateway.external.parentRefs) }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.gateway.letsencrypt.clusterIssuerName }}
spec:
  acme:
    email: {{ .Values.gateway.letsencrypt.email }}
    server: {{ .Values.gateway.letsencrypt.server }}
    privateKeySecretRef:
      name: {{ .Values.gateway.letsencrypt.secretName }}
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "documentserver") }}
                namespace: {{ include "ds.namespace" . | quote }}
                kind: Gateway
                group: gateway.networking.k8s.io
{{- end }}