apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: documentserver
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - kube-ds.teamlab.info
    secretName: tls
  rules:
  - host: kube-ds.teamlab.info
    http:
      paths:
      - path: /
        backend:
          serviceName: documentserver
          servicePort: 8888
      - path: /example
        backend:
          serviceName: example
          servicePort: 8888
