kind: Service
apiVersion: v1
metadata:
  name: docservice
spec:
  selector:
    app: docservice
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
