kind: Service
apiVersion: v1
metadata:
  name: docservice
spec:
  selector:
    app: docservice
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.docservice.containerPorts.http }}
      targetPort: {{ .Values.docservice.containerPorts.http }}
  type: ClusterIP
