kind: Service
apiVersion: v1
metadata:
  name: documentserver
{{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ tpl $value $ }}
    {{- end }}
{{- end }}
spec:
  selector:
    app: docservice
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8888
  type: {{ .Values.service.type }}
