{{- if eq (include "ds.svc.create" .) "true" }}
kind: Service
apiVersion: v1
metadata:
  name: documentserver
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ tpl $value $ }}
    {{- end }}
  {{- end }}
spec:
  selector:
    app: docservice
    {{- if .Values.commonLabels }}
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.proxy.containerPorts.http }}
  type: {{ .Values.service.type }}
{{- end }}
