kind: Service
apiVersion: v1
metadata:
  name: documentserver
spec:
  selector:
    app: docservice
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.dsServicePort }}
      targetPort: 8888 
  type: {{ .Values.service.dsServiceType }}
