kind: Service
apiVersion: v1
metadata:
  name: spellchecker
spec:
  selector:
    app: spellchecker
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
