kind: Service
apiVersion: v1
metadata:
  name: documentserver
spec:
  selector:
    app: docservice
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
