{{- if eq (include "ds.pvc.create" .) "true" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ds-files
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
