apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ds-files-minikube
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
