{{- if and (not .Values.persistence.storageS3) .Values.docservice.plugins }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plugins
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations: 
    {{- if or .Values.commonAnnotations .Values.persistence.annotations }}
    {{- $dictValue := default .Values.commonAnnotations .Values.persistence.annotations }}
    {{- include "ds.annotations.commonAnnotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
