{{- if .Values.example.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example
  labels:
    app: example
spec:
  selector:
    matchLabels:
      app: example
  serviceName: example
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: example
      {{- if .Values.example.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.example.podAnnotations }}
        {{ $key }}: {{ tpl $value $ }}
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.securityContext.example.runAsUser }}
        runAsGroup: {{ .Values.securityContext.example.runAsGroup }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 4 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 4 }}
      {{- end }}
      containers:
      - name: example
        image: {{ .Values.example.containerImage | quote }}
        imagePullPolicy: {{ .Values.example.imagePullPolicy }}
        ports:
        - containerPort: 3000
          name: http
        resources: {{ toYaml .Values.example.resources | nindent 10 }}
        envFrom:
        - secretRef:
            name: {{ template "ds.jwt.secretName" . }}
        - configMapRef:
            name: example
{{- end }}
