apiVersion: batch/v1
kind: Job
metadata:
  name: prepare4shutdown
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
        - name: ds-files
          persistentVolumeClaim:
            claimName: ds-files
        - name: remove-db-scripts
          configMap:
            name: remove-db-scripts
      containers:
        - name: prepare4shutdown
          image: postgres
          envFrom:
          - configMapRef:
              name: documentserver
          env:
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgresql-password
          volumeMounts:
          - name: ds-files
            mountPath: /var/lib/onlyoffice/documentserver/App_Data/cache/files
          - name: remove-db-scripts
            mountPath: "/tmp/removetbl.sql"
            subPath: "removetbl.sql"

          command: ["bash"]
          args: ["-c", "apt update;
            apt install curl;
            curl -v http://docservice:8000/internal/cluster/inactive -X PUT -s -o /dev/null; 
            rm -rf /var/lib/onlyoffice/documentserver/App_Data/cache/files/*;
            PGPASSWORD=$DB_PWD psql --host=postgresql --user=postgres --file=/tmp/removetbl.sql;
            ls -l /tmp;
            echo work done"]
      restartPolicy: Never
