apiVersion: batch/v1
kind: Job
metadata:
  name: prepare4update
spec:
  template:
    spec:
      volumes:
        - name: ds-files
          persistentVolumeClaim:
            claimName: ds-files
        - name: remove-db-scripts
          configMap:
            name: remove-db-scripts
        - name: init-db-scripts
          configMap:
            name: init-db-scripts
        - name: prepare4update-script
          configMap:
            name: prepare4update-script
      containers:
        - name: prepare4update
          image: postgres
          envFrom:
          - configMapRef:
              name: documentserver
          env:
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgresql-password
          volumeMounts:
          - name: ds-files
            mountPath: /var/lib/onlyoffice/documentserver/App_Data/cache/files
          - name: remove-db-scripts
            mountPath: /sql/removetbl/
          - name: init-db-scripts
            mountPath: /sql/createdb/
          - name: prepare4update-script
            mountPath: /scripts/

          command: 
          - /bin/bash
          - /scripts/prepare4update-script.sh
      restartPolicy: Never
