apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.name }}
type: Opaque
immutable: true
stringData:
  DB_USER: {{ .Values.database.dbUser | quote }}
  DB_PWD: {{ .Values.database.dbPassword | quote }}
