{{- if eq (include "ds.db.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
type: Opaque
stringData:
  {{ .Values.connections.dbSecretKeyName }}: {{ include "ds.db.password" . | quote }}
{{- end }}
