{{- if eq (include "ds.info.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ include "ds.resources.name" (list . .Values.commonNameSuffix "info-auth") }}
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "ds.annotations.commonAnnotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.proxy.infoAllowedSecretKeyName }}: {{ include "ds.info.password" . | quote }}
{{- end }}
