apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwt.name }}
type: Opaque
immutable: true
stringData:
  JWT_ENABLED: {{ .Values.jwt.jwtEnabled | quote }}
  JWT_SECRET: {{ .Values.jwt.jwtSecret | quote }}
