{{- if eq (include "ds.license.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: license
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
type: Opaque
{{- end }}
