{{- if eq (include "ds.license.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: license
type: Opaque
data:
{{ (.Files.Glob "sources/license/license.lic").AsSecrets | indent 2 }}
{{- end }}
