apiVersion: v1
kind: Secret
metadata:
  {{- $secretName := include "ds.resources.name" (list . .Values.commonNameSuffix "link-secret") }}
  name: {{ $secretName }}
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "ds.annotations.commonAnnotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  SECURE_LINK_SECRET: {{ include "ds.secrets.lookup" (list . .Values.proxy.secureLinkSecret $secretName "SECURE_LINK_SECRET") | quote }}
