{{- if eq (include "ds.postgresql.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
type: Opaque
stringData:
  postgresql-password: {{ include "ds.postgresql.password" . | quote }}
{{- end }}
