{{- if eq (include "ds.rabbitmq.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.connections.amqpSecretKeyName }}: {{ include "ds.rabbitmq.password" . | quote }}
{{- end }}
