{{- if eq (include "ds.redis.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis
type: Opaque
stringData:
  {{ .Values.connections.redisSecretKeyName }}: {{ include "ds.redis.password" . | quote }}
{{- end }}
