{{- if and (eq (include "ds.redis.sentinel.createSecret" .) "true") (eq .Values.connections.redisConnectorName "ioredis") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-sentinel
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "ds.annotations.commonAnnotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.connections.redisSentinelSecretKeyName }}: {{ include "ds.redis.sentinel.password" . | quote }}
{{- end }}
