{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: documentserver
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  {{ if .Values.ingress.ssl }}
  tls: 
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.secret }}
  {{ end }}
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: documentserver
          servicePort: 8888
{{ end }}
