{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "documentserver") }}
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if or .Values.commonAnnotations .Values.ingress.annotations }}
  {{- $dictValue := default .Values.commonAnnotations .Values.ingress.annotations }}
  annotations: {{- include "ds.annotations.commonAnnotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
  {{- end }}
    {{- if not (eq .Values.ingress.path "/") }}
    nginx.ingress.kubernetes.io/x-forwarded-prefix: {{ .Values.ingress.path }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.ssl.enabled }}
  tls: 
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.ssl.secret }}
  {{- end }}
  rules:
  {{- if .Values.ingress.host }}
  - host: {{ .Values.ingress.host }}
  {{- else }}
  - host:
  {{- end }}
    http:
      paths:
      - path: {{ template "ds.ingress.path" . }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "ds.svc.name" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
