{{ if .Values.service.ingress }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: documentserver
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: documentserver
          servicePort: 8888
{{ end }}
