{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "documentserver") }}
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    {{- if or .Values.commonAnnotations .Values.ingress.annotations }}
      {{- $dictValue := default .Values.commonAnnotations .Values.ingress.annotations }}
      {{- include "ds.annotations.commonAnnotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if and (not (eq .Values.ingress.path "/")) (eq "ingress-nginx" .Values.ingress.controllerName) }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "{{ include "ds.path.withoutTrailingSlash" .Values.ingress.path }}"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- else if and (not (eq .Values.ingress.path "/")) (eq "nginx-ingress" .Values.ingress.controllerName) }}
    nginx.org/websocket-services: "{{ include "ds.svc.name" . }}"
    nginx.org/rewrites: "serviceName={{ include "ds.svc.name" . }} rewrite=/"
    nginx.org/proxy-set-headers: |
      X-Forwarded-Prefix: {{ include "ds.path.withoutTrailingSlash" .Values.ingress.path }},
      X-Scheme
    {{- else if and (not (eq .Values.ingress.path "/")) (eq "haproxytech" .Values.ingress.controllerName) }}
    haproxy.org/backend-config-snippet: |
      acl existing-x-forwarded-host req.hdr(X-Forwarded-Host) -m found
      http-request add-header X-Forwarded-Prefix {{ include "ds.path.withoutTrailingSlash" .Values.ingress.path }} unless existing-x-forwarded-host
      http-request replace-path {{ include "ds.path.withoutTrailingSlash" .Values.ingress.path }}[/]?(.*) /\1
    {{- else if and (not (eq .Values.ingress.path "/")) (eq "kong" .Values.ingress.controllerName) }}
    konghq.com/strip-path: "true"
    {{- else if and (not (eq .Values.ingress.path "/")) (eq "traefik" .Values.ingress.controllerName) }}
    traefik.ingress.kubernetes.io/router.middlewares: "documentserver@kubernetescrd"
    {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.ssl.enabled }}
  tls: 
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.ssl.secret }}
  {{- end }}
  rules:
  {{- if .Values.ingress.host }}
  - host: {{ .Values.ingress.host }}
  {{- else }}
  - host:
  {{- end }}
    http:
      paths:
      - path: {{ include "ds.path.withTrailingSlash" .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: {{ include "ds.svc.name" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
