{{- if .Values.metrics.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  {{ if .Values.ingress.ssl.enabled }}
  tls:
  - hosts:
    - example.com
    secretName: {{ .Values.ingress.ssl.secret }}
  {{ end }}
  rules:
  {{ if .Values.ingress.ssl.enabled }}
  - host: {{ .Values.ingress.ssl.host }}
  {{ else }}
  - host:
  {{ end }}
    http:
      paths:
      - path: /grafana/
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 80
{{- end }}