{{ if .Values.example.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: example
spec:
  {{ if .Values.securityContext.enabled }}
  securityContext:
    runAsUser: {{ .Values.securityContext.exampleUser }}
    runAsGroup: {{ .Values.securityContext.exampleGroup }}
  {{ end }}
  containers:
    - name: example
      image: {{ .Values.example.containerImage | quote }}
      ports:
        - containerPort: 3000
      envFrom:
        - secretRef:
            name: jwt
        - configMapRef:
              name: example
{{ end }}
