{{ if .Values.example.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: example
spec:
  {{- if .Values.example.podAnnotations }}
  annotations:
    {{- range $key, $value := .Values.example.podAnnotations }}
    {{ $key }}: {{ tpl $value $ }}
    {{- end }}
  {{- end }}
  {{ if .Values.securityContext.enabled }}
  securityContext:
    runAsUser: {{ .Values.securityContext.example.runAsUser }}
    runAsGroup: {{ .Values.securityContext.example.runAsGroup }}
  {{ end }}
  {{- if .Values.nodeSelector }}
  nodeSelector: {{ toYaml .Values.nodeSelector | nindent 4 }}
  {{- end }}
  {{- if .Values.tolerations }}
  tolerations: {{ toYaml .Values.tolerations | nindent 4 }}
  {{- end }}
  containers:
    - name: example
      image: {{ .Values.example.containerImage | quote }}
      imagePullPolicy: {{ .Values.example.imagePullPolicy }}
      ports:
        - containerPort: 3000
      resources: {{ toYaml .Values.example.resources | nindent 8 }}
      envFrom:
        - secretRef:
            name: {{ template "ds.jwt.secretName" . }}
        - configMapRef:
              name: example
{{ end }}
