{{ if .Values.example.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: example
spec:
  {{ if .Values.securityContext.enabled }}
  securityContext:
    runAsUser: {{ .Values.securityContext.example.runAsUser }}
    runAsGroup: {{ .Values.securityContext.example.runAsGroup }}
  {{ end }}
  containers:
    - name: example
      image: {{ .Values.example.containerImage | quote }}
      imagePullPolicy: {{ .Values.example.imagePullPolicy }}
      ports:
        - containerPort: 3000
      resources: {{ toYaml .Values.example.resources | nindent 8 }}
      envFrom:
        - secretRef:
            name: jwt
        - configMapRef:
              name: example
{{ end }}
