{{- if .Values.example.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.example.name }}
  labels:
    app: {{ .Values.example.name }}
spec:
  containers:
    - name: {{ .Values.example.name }}
      image: {{ .Values.example.containerImage | quote }}
      ports:
        - containerPort: 3000
      envFrom:
        - secretRef:
            name: jwt
        - configMapRef:
              name: {{ .Values.example.name }}
{{- end -}}
