{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: check-ready-db
data:
  checkReadyDB.sh: |-
    #!/bin/bash
    for ((i=1 ; i <= 30 ; i++)); do
      {{- if eq .Values.connections.dbType "postgres" }}
      pg_isready --host={{ template "ds.db.host" . }} \
        --port={{ .Values.connections.dbPort }} \
        --user={{ .Values.connections.dbUser }}
      {{- else if or (eq .Values.connections.dbType "mysql") (eq .Values.connections.dbType "mariadb") }}
      mysql -h {{ template "ds.db.host" . }} \
        -P {{ .Values.connections.dbPort }} \
        -u {{ .Values.connections.dbUser }} \
        -p$DB_PWD \
        -e "show databases;" > /dev/null
      {{- end }}
      if [ $? -ne 0 ]; then
        sleep 5
      else
        echo -e "\e[0;32m DB is ready to accept connections \e[0m"
        DB_READY='yes'
        break
      fi
    done
    if [[ "${DB_READY}" != 'yes' ]]; then
      echo -e "\e[0;31m DB is not available \e[0m"
      exit 1
    fi
{{- end }}
