apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
    - name: db
      image: onlyoffice/4testing-ds-db:latest
      env:
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: db
            key: DB_USER
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db
            key: DB_PWD
      ports:
      - containerPort: 5432