apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: example
spec:
#  securityContext:
#    runAsUser: 101
#    runAsGroup: 101
  containers:
    - name: example
      image: onlyoffice/docs-example-de:6.3.1.32
      ports:
        - containerPort: 3000
      envFrom:
        - secretRef:
            name: jwt
        - configMapRef:
              name: example
