apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: example
spec:
#  securityContext:
#    runAsUser: 1001
#    runAsGroup: 1001
  containers:
    - name: example
      image: onlyoffice/docs-example:6.3.1.32
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "250m"
      ports:
        - containerPort: 3000
      envFrom:
        - secretRef:
            name: jwt
        - configMapRef:
              name: example
