apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: example
spec:
  volumes:
    - name: example
      configMap:
        name: example
  containers:
    - name: example
      image: onlyoffice/4testing-ds-example:latest
      envFrom:
        - secretRef:
            name: jwt
        - configMapRef:
            name: example
      ports:
        - containerPort: 3000