apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: example
spec:
  volumes:
    - name: nginx-conf
      configMap:
        name: example
  containers:
    - name: proxy
      image: nginx
      ports:
        - containerPort: 8888      
      volumeMounts:
      - name: nginx-conf
        mountPath: /etc/nginx/conf.d/nginx.conf
        subPath: nginx.conf
        readOnly: true


    - name: example
      image: onlyoffice/4testing-ds-example:5.5.3
      envFrom:
        - secretRef:
            name: jwt
