name: Integrations test

run-name: >
  Integrations tests on PR: "${{ github.event.pull_request.title }}" by @${{ github.actor }}
  
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - 'master'
    paths-ignore:
      - '.github/**'
      - '**/README.md'
      - '**/CHANGELOG.md'
      - '**/LICENSE'    

permissions:
  # All other permissions are set to none
  contents: read
  packages: read

env: 
  INSTALL_SCRIPT: './sources/scripts/deploy-${{ github.event.repository.name }}.sh'
  K8S_STORAGE_CLASS: "standard"
  NFS_PERSISTANCE_SIZE: "8Gi"

jobs:
  spin-up:
    name: integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chart
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - uses: azure/setup-helm@v3
        id: setup-helm
        with:
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: setup kind k8s
        id: setup-kind-k8s
        uses: helm/kind-action@v1.4.0
        with: 
          config: ./sources/kind-config.yaml

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Start deploy
        run: | 
            set -euo pipefail 
            
            export K8S_STORAGE_CLASS=${K8S_STORAGE_CLASS}
            export NFS_PERSISTANCE_SIZE=${NFS_PERSISTANCE_SIZE}
            sudo chmod +x ${INSTALL_SCRIPT}
            bash ${INSTALL_SCRIPT}     
