apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource
type: Opaque
stringData:
  prometheus.yaml: |    
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: prometheus-server
        editable: true
